<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net472</TargetFramework><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.VisualStudio.Interop" Version="17.14.40260" />
  </ItemGroup>
</Project>
